## List

In [1]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [5]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [7]:
for rec in zip(a, b):
    print(rec[0] + rec[1])

3
7
11
15
19


## Numpy

In [8]:
import numpy
numpy.array(a)

array([1, 3, 5, 7, 9])

In [9]:
import numpy as np
na = np.array(a)
nb = np.array(b)

In [12]:
nb + na

array([ 3,  7, 11, 15, 19])

In [13]:
nb - na

array([1, 1, 1, 1, 1])

In [14]:
nb * na

array([ 2, 12, 30, 56, 90])

In [15]:
na

array([1, 3, 5, 7, 9])

In [16]:
na[0]

1

In [17]:
na[1:3]

array([3, 5])

In [18]:
na > 3

array([False, False,  True,  True,  True])

In [19]:
na[na > 3]

array([5, 7, 9])

In [20]:
na = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
na[0,0]

1

In [22]:
na[  0 ,  : ]

array([1, 2, 3, 4, 5])

In [23]:
na[:, 0]

array([1, 6])

In [24]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [25]:
a = np.array([[1,2,3,4,5]])
b = np.array([[0,0,1], [0,0,2], [1,0,1],[0,0,2], [0,1,2]])

In [27]:
a.shape
b.shape

(5, 3)

In [29]:
a.dot(b)

array([[ 3,  5, 26]])