## List

In [1]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [5]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [7]:
for rec in zip(a, b):
    print(rec[0] + rec[1])

3
7
11
15
19


## Numpy

In [8]:
import numpy
numpy.array(a)

array([1, 3, 5, 7, 9])

In [9]:
import numpy as np
na = np.array(a)
nb = np.array(b)

In [12]:
nb + na

array([ 3,  7, 11, 15, 19])

In [13]:
nb - na

array([1, 1, 1, 1, 1])

In [14]:
nb * na

array([ 2, 12, 30, 56, 90])

In [15]:
na

array([1, 3, 5, 7, 9])

In [16]:
na[0]

1

In [17]:
na[1:3]

array([3, 5])

In [18]:
na > 3

array([False, False,  True,  True,  True])

In [19]:
na[na > 3]

array([5, 7, 9])

In [20]:
na = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
na[0,0]

1

In [22]:
na[  0 ,  : ]

array([1, 2, 3, 4, 5])

In [23]:
na[:, 0]

array([1, 6])

In [24]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [25]:
a = np.array([[1,2,3,4,5]])
b = np.array([[0,0,1], [0,0,2], [1,0,1],[0,0,2], [0,1,2]])

In [27]:
a.shape
b.shape

(5, 3)

In [29]:
a.dot(b)

array([[ 3,  5, 26]])

In [32]:
c = np.array([[30, 10000],\
              [25, 5000 ],\
              [40, 8000 ]])

In [35]:
np.mean(c[:,0])

31.666666666666668

In [36]:
c = np.array([['david', 30, 10000],\
              ['marry',25, 5000 ],\
              ['peter',40, 8000 ]])

In [37]:
c

array([['david', '30', '10000'],
       ['marry', '25', '5000'],
       ['peter', '40', '8000']], dtype='<U5')

In [38]:
c = np.array([['name', 'age', 'salary'],\
              ['david', 30, 10000],\
              ['marry',25, 5000 ],\
              ['peter',40, 8000 ]])

In [39]:
c

array([['name', 'age', 'salary'],
       ['david', '30', '10000'],
       ['marry', '25', '5000'],
       ['peter', '40', '8000']], dtype='<U6')

In [43]:
np.mean(c[1:,1].astype(int))

31.666666666666668

In [46]:
import pandas as pd
df = pd.DataFrame([['david', 30, 10000],\
                   ['marry',25, 5000 ],\
                   ['peter',40, 8000 ]], columns=['name', 'age', 'salary'])

In [47]:
df

name  age  salary
0  david   30   10000
1  marry   25    5000
2  peter   40    8000

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
name      3 non-null object
age       3 non-null int64
salary    3 non-null int64
dtypes: int64(2), object(1)
memory usage: 152.0+ bytes


In [49]:
df.age.mean()

31.666666666666668

In [50]:
df.salary.mean()

7666.666666666667

## Pandas Series

In [54]:
# List
[21000, 18900, 18000, 'hello']

[21000, 18900, 18000, 'hello']

In [55]:
# numpy array
np.array([21000, 18900, 18000, 'hello'])

array(['21000', '18900', '18000', 'hello'], dtype='<U21')

In [56]:
# pandas Series
pd.Series([21000, 18900, 18000, 'hello'])

0    21000
1    18900
2    18000
3    hello
dtype: object

In [57]:
s = pd.Series([21000, 18900, 18000]) 
s


0    21000
1    18900
2    18000
dtype: int64

In [58]:
pd.Series([21000, 18900, 18000], index = ['Iphone', 'Edge S7', 'HTC M1'])

Iphone     21000
Edge S7    18900
HTC M1     18000
dtype: int64

In [60]:
s = pd.Series({'Iphone':21000,'Edge S7':18900,'HTC M1':18000})
s

Edge S7    18900
HTC M1     18000
Iphone     21000
dtype: int64

In [61]:
s[2]

21000

In [62]:
s[-1]

21000

In [63]:
s[1:3]

HTC M1    18000
Iphone    21000
dtype: int64

In [64]:
s['Iphone']

21000

In [65]:
s[['Iphone', 'Edge S7']]

Iphone     21000
Edge S7    18900
dtype: int64

In [66]:
s < 20000

Edge S7     True
HTC M1      True
Iphone     False
dtype: bool

In [67]:
cheap = s < 20000
cheap

Edge S7     True
HTC M1      True
Iphone     False
dtype: bool

In [68]:
s[cheap]

Edge S7    18900
HTC M1     18000
dtype: int64

In [69]:
s[s < 20000]

Edge S7    18900
HTC M1     18000
dtype: int64

In [71]:
s['Iphone'] = 20000

In [72]:
s

Edge S7    18900
HTC M1     18000
Iphone     20000
dtype: int64

In [73]:
s[s < 20000] * 0.8

Edge S7    15120.0
HTC M1     14400.0
dtype: float64

In [74]:
s[s < 20000] = s[s < 20000] * 0.8

In [75]:
s

Edge S7    15120
HTC M1     14400
Iphone     20000
dtype: int64

In [76]:
'Iphone' in s

True

In [77]:
'mi' in s

False

In [78]:
s

Edge S7    15120
HTC M1     14400
Iphone     20000
dtype: int64

In [79]:
s * 0.8

Edge S7    12096.0
HTC M1     11520.0
Iphone     16000.0
dtype: float64

In [80]:
np.sqrt(s)

Edge S7    122.963409
HTC M1     120.000000
Iphone     141.421356
dtype: float64

In [81]:
s.min()

14400

In [82]:
s.max()

20000

In [83]:
s.describe()

count        3.000000
mean     16506.666667
std       3046.659373
min      14400.000000
25%      14760.000000
50%      15120.000000
75%      17560.000000
max      20000.000000
dtype: float64

In [85]:
S2 = s[['Iphone', 'HTC M1']] + s[['mi', 'HTC M1']]
S2

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pandas/core/series.py:705: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


HTC M1    28800.0
Iphone        NaN
mi            NaN
dtype: float64

In [86]:
S2.isnull()

HTC M1    False
Iphone     True
mi         True
dtype: bool

In [87]:
S2.notnull()

HTC M1     True
Iphone    False
mi        False
dtype: bool