## Python List

In [1]:
s= [5,7,9,'s']
type(s)

list

In [3]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
len(a)

5

In [5]:
len(b)

5

In [7]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [8]:
for i in zip(a,b):
    print(i)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [9]:
for i,j in zip(a,b):
    print(i,j)

1 2
3 4
5 6
7 8
9 10


In [10]:
for i,j in zip(a,b):
    print(i*j)

2
12
30
56
90


In [11]:
import numpy as np
na = np.array(a)
nb = np.array(b)
type(na)

numpy.ndarray

In [12]:
na

array([1, 3, 5, 7, 9])

In [14]:
a.append('s')
a

[1, 3, 5, 7, 9, 's']

In [15]:
na.append('s')

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
s= [5,7,9,'s']
np.array(s)

array(['5', '7', '9', 's'], dtype='<U21')

In [20]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [21]:
na = np.array(a)
na

array([1, 3, 5, 7, 9])

In [22]:
nb = np.array(b)
nb

array([ 2,  4,  6,  8, 10])

In [23]:
na * nb

array([ 2, 12, 30, 56, 90])

In [24]:
na + nb

array([ 3,  7, 11, 15, 19])

In [25]:
na -nb

array([-1, -1, -1, -1, -1])

In [26]:
na / nb

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])

## Numpy 

In [27]:
import numpy as np
my_list = [1,2,3]
np.array(my_list)


array([1, 2, 3])

In [28]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
range(10)

range(0, 10)

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [37]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.rand(2)



array([0.37172501, 0.28720286])

In [40]:
np.random.rand(5,5)

array([[0.48347588, 0.95365821, 0.30814824, 0.75435334, 0.9814912 ],
       [0.58394118, 0.37184154, 0.64289289, 0.13801966, 0.27089985],
       [0.2507565 , 0.76714165, 0.74086884, 0.33397597, 0.56155791],
       [0.6274942 , 0.71120303, 0.76818589, 0.88443558, 0.82211995],
       [0.7901024 , 0.98210086, 0.26639973, 0.21558765, 0.36740387]])

In [43]:
?np.random.rand

In [45]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolut

In [41]:
np.random.randn(2)


array([0.19800348, 0.88378208])

In [42]:
np.random.randn(5,5)


array([[ 0.14938172, -0.41805334,  0.44679187,  0.32216269,  0.63745418],
       [-0.07855987, -1.32178234,  1.01316403, -0.07862018, -1.12695927],
       [-0.52409901,  0.46825607,  1.1615208 ,  1.15041686,  0.45108324],
       [-0.92549083,  0.71513178,  1.00650602, -0.28197333, -1.43235279],
       [-1.469169  , -0.87496869,  1.7754499 , -0.74384819, -2.48826046]])

In [46]:
?np.random.randn

In [47]:
np.random.randint(1,100)

77

In [48]:
np.random.randint(1,100,10)

array([75, 23, 43, 11, 26, 85, 66, 85, 55, 82])

In [50]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.shape

(25,)

In [52]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr = np.random.randint(0,50,10)


In [54]:
ranarr

array([24, 37, 21, 19, 10, 18, 31, 22, 29, 46])

In [55]:
ranarr.max()

46

In [56]:
ranarr.min()

10

In [57]:
ranarr.argmax()

9

In [58]:
ranarr.argmin()

4

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.shape

(25,)

In [63]:
arr.reshape(1,25)
arr.reshape(1,25).shape

(1, 25)

In [64]:
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(25,1).shape


(25, 1)

In [66]:
arr.dtype


dtype('int64')

In [67]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_arr[:] = 99

In [76]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr = np.arange(0,11)
#arr
slice_of_arr2 = arr[0:6].copy()
slice_of_arr2[:] = 99
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[1]

array([20, 25, 30])

In [83]:
arr_2d[1][0]

20

In [84]:
arr_2d[1,0]

20

In [85]:
arr_2d[2]

array([35, 40, 45])

In [86]:
arr_2d[2,:]


array([35, 40, 45])

In [88]:
arr_2d[2,1:3]

array([40, 45])

In [ ]:
arr_2d[2,1:3]

In [89]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
?np.random.randn

In [104]:
a = np.random.randn(3,3)

array([[ 1.17234638,  0.93537781, -0.86630906],
       [-0.15121333, -0.61018894,  0.12731845],
       [-0.00871705,  0.15407639, -0.06681719]])

In [105]:
a.max()

1.172346376222158

In [106]:
a.min()

-0.8663090571350679

In [107]:
print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [111]:
(a - a.min()) / (a.max() - a.min())

array([[1.        , 0.88376233, 0.        ],
       [0.35076832, 0.12563188, 0.48739355],
       [0.4206655 , 0.50051884, 0.39216626]])

In [114]:
?np.random.uniform

In [116]:
np.random.uniform(0,1, size=(3,3))

array([[0.37510014, 0.38539635, 0.16512507],
       [0.61826014, 0.63374269, 0.05854548],
       [0.44143238, 0.55401303, 0.62661967]])

In [118]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [120]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [121]:
arr[arr != 4]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [122]:
arr[(arr > 4) & (arr < 8)]

array([5, 6, 7])

In [123]:
bool_arr = arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [124]:
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
arr * arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [127]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
arr/arr

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [129]:
1/ 0 

ZeroDivisionError: division by zero

In [130]:
a = np.array(['1','2','3'])
a + a

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U1') dtype('<U1') dtype('<U1')

In [131]:
arr2 = arr/arr

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [135]:
arr2 == 1

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
arr[4:7]

array([4, 5, 6])

In [140]:
arr  +3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
1/arr


/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [142]:
arr**3 

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [149]:
3 ^ 5
#011
#101
#====
#110

6

In [150]:
#help('^')

In [144]:
3 ** 5

243

In [151]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [152]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [153]:
np.max(arr)


9

In [154]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [155]:
np.log(arr)

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])