## Python List

In [1]:
s= [5,7,9,'s']
type(s)

list

In [3]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
len(a)

5

In [5]:
len(b)

5

In [7]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [8]:
for i in zip(a,b):
    print(i)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [9]:
for i,j in zip(a,b):
    print(i,j)

1 2
3 4
5 6
7 8
9 10


In [10]:
for i,j in zip(a,b):
    print(i*j)

2
12
30
56
90


In [11]:
import numpy as np
na = np.array(a)
nb = np.array(b)
type(na)

numpy.ndarray

In [12]:
na

array([1, 3, 5, 7, 9])

In [14]:
a.append('s')
a

[1, 3, 5, 7, 9, 's']

In [15]:
na.append('s')

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
s= [5,7,9,'s']
np.array(s)

array(['5', '7', '9', 's'], dtype='<U21')

In [20]:
a = [1,3,5,7,9]
b = [2,4,6,8,10]

In [21]:
na = np.array(a)
na

array([1, 3, 5, 7, 9])

In [22]:
nb = np.array(b)
nb

array([ 2,  4,  6,  8, 10])

In [23]:
na * nb

array([ 2, 12, 30, 56, 90])

In [24]:
na + nb

array([ 3,  7, 11, 15, 19])

In [25]:
na -nb

array([-1, -1, -1, -1, -1])

In [26]:
na / nb

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])

## Numpy 

In [27]:
import numpy as np
my_list = [1,2,3]
np.array(my_list)


array([1, 2, 3])

In [28]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
range(10)

range(0, 10)

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.linspace(0,10,3)


array([ 0.,  5., 10.])

In [37]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.rand(2)



array([0.37172501, 0.28720286])

In [40]:
np.random.rand(5,5)

array([[0.48347588, 0.95365821, 0.30814824, 0.75435334, 0.9814912 ],
       [0.58394118, 0.37184154, 0.64289289, 0.13801966, 0.27089985],
       [0.2507565 , 0.76714165, 0.74086884, 0.33397597, 0.56155791],
       [0.6274942 , 0.71120303, 0.76818589, 0.88443558, 0.82211995],
       [0.7901024 , 0.98210086, 0.26639973, 0.21558765, 0.36740387]])

In [43]:
?np.random.rand

In [45]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolut

In [41]:
np.random.randn(2)


array([0.19800348, 0.88378208])

In [42]:
np.random.randn(5,5)


array([[ 0.14938172, -0.41805334,  0.44679187,  0.32216269,  0.63745418],
       [-0.07855987, -1.32178234,  1.01316403, -0.07862018, -1.12695927],
       [-0.52409901,  0.46825607,  1.1615208 ,  1.15041686,  0.45108324],
       [-0.92549083,  0.71513178,  1.00650602, -0.28197333, -1.43235279],
       [-1.469169  , -0.87496869,  1.7754499 , -0.74384819, -2.48826046]])

In [46]:
?np.random.randn

In [47]:
np.random.randint(1,100)

77

In [48]:
np.random.randint(1,100,10)

array([75, 23, 43, 11, 26, 85, 66, 85, 55, 82])

In [50]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.shape

(25,)

In [52]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr = np.random.randint(0,50,10)


In [54]:
ranarr

array([24, 37, 21, 19, 10, 18, 31, 22, 29, 46])

In [55]:
ranarr.max()

46

In [56]:
ranarr.min()

10

In [57]:
ranarr.argmax()

9

In [58]:
ranarr.argmin()

4

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.shape

(25,)

In [63]:
arr.reshape(1,25)
arr.reshape(1,25).shape

(1, 25)

In [64]:
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(25,1).shape


(25, 1)

In [66]:
arr.dtype


dtype('int64')

In [67]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_arr[:] = 99

In [76]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr = np.arange(0,11)
#arr
slice_of_arr2 = arr[0:6].copy()
slice_of_arr2[:] = 99
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[1]

array([20, 25, 30])

In [83]:
arr_2d[1][0]

20

In [84]:
arr_2d[1,0]

20

In [85]:
arr_2d[2]

array([35, 40, 45])

In [86]:
arr_2d[2,:]


array([35, 40, 45])

In [88]:
arr_2d[2,1:3]

array([40, 45])

In [ ]:
arr_2d[2,1:3]

In [89]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
?np.random.randn

In [104]:
a = np.random.randn(3,3)

array([[ 1.17234638,  0.93537781, -0.86630906],
       [-0.15121333, -0.61018894,  0.12731845],
       [-0.00871705,  0.15407639, -0.06681719]])

In [105]:
a.max()

1.172346376222158

In [106]:
a.min()

-0.8663090571350679

In [107]:
print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [111]:
(a - a.min()) / (a.max() - a.min())

array([[1.        , 0.88376233, 0.        ],
       [0.35076832, 0.12563188, 0.48739355],
       [0.4206655 , 0.50051884, 0.39216626]])

In [114]:
?np.random.uniform

In [116]:
np.random.uniform(0,1, size=(3,3))

array([[0.37510014, 0.38539635, 0.16512507],
       [0.61826014, 0.63374269, 0.05854548],
       [0.44143238, 0.55401303, 0.62661967]])

In [118]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [120]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [121]:
arr[arr != 4]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [122]:
arr[(arr > 4) & (arr < 8)]

array([5, 6, 7])

In [123]:
bool_arr = arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [124]:
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
arr * arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [127]:
arr - arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
arr/arr

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [129]:
1/ 0 

ZeroDivisionError: division by zero

In [130]:
a = np.array(['1','2','3'])
a + a

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U1') dtype('<U1') dtype('<U1')

In [131]:
arr2 = arr/arr

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [135]:
arr2 == 1

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
arr[4:7]

array([4, 5, 6])

In [140]:
arr  +3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
1/arr


/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [142]:
arr**3 

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [149]:
3 ^ 5
#011
#101
#====
#110

6

In [150]:
#help('^')

In [144]:
3 ** 5

243

In [151]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [152]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [153]:
np.max(arr)


9

In [154]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [155]:
np.log(arr)

/Users/davidchiu/.pyenv/versions/3.6.2/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [156]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [157]:
?np.random.randn

## Pandas

In [158]:
na = np.array([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na               


array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [159]:
na[:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U5')

In [160]:
na[:,2].astype(int)

array([29, 23, 35, 33, 21, 20])

In [161]:
na[:,2].astype(int).sum()

161

In [162]:
import numpy as np
na = np.array([['name', 'gender', 'age'], ['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
na 


array([['name', 'gender', 'age'],
       ['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U6')

In [167]:
na[:,2][1:].astype(int).mean()

26.833333333333332

In [168]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df


0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [169]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [170]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [173]:
%autosave 0

Autosave disabled


## Pandas Series

In [174]:
# 建立Series
import numpy  as np
import pandas as pd

# 從List 建立Series
labels  = ['a','b','c']
my_list = [10,20,30]

pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [176]:
np.array(my_list)

array([10, 20, 30])

In [175]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [177]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [179]:
arr = np.array([10,20,30])
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [180]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [181]:
d = {'a':10,'b':20,'c':30}
pd.Series(d)


a    10
b    20
c    30
dtype: int64

In [182]:
pd.Series((1,2,3))

0    1
1    2
2    3
dtype: int64

In [183]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])


In [184]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [185]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [186]:
ser1['USA']


1

In [187]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [193]:
(ser1 + ser2).fillna(0)

Germany    4.0
Italy      0.0
Japan      8.0
USA        2.0
USSR       0.0
dtype: float64

In [198]:
s1 = ser1[ser1.index | ser2.index].fillna(0)
s2 = ser2[ser1.index | ser2.index].fillna(0)
s1 + s2

Germany    4.0
Italy      5.0
Japan      8.0
USA        2.0
USSR       3.0
dtype: float64

In [200]:
ser1.add(ser2, fill_value=0)

Germany    4.0
Italy      5.0
Japan      8.0
USA        2.0
USSR       3.0
dtype: float64

In [256]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]])
df


0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [257]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [258]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]], columns = ['name', 'gender', 'age'])
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [259]:
df = pd.DataFrame([{'name':'frank', 'gender':'M', 'age':29}, \
                   {'name':'mary',  'gender':'F', 'age':23}, \
                   {'name':'tom',   'gender':'M', 'age':35}, \
                   {'name':'ted',   'gender':'M', 'age':33}, \
                   {'name':'jean',  'gender':'F', 'age':21}, \
                   {'name':'lisa',  'gender':'F', 'age':20}])
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [260]:
df.head()

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean

In [261]:
df.head(3)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom

In [262]:
df.tail()

age gender  name
1   23      F  mary
2   35      M   tom
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [263]:
?df.tail

In [264]:
df.tail(3)

age gender  name
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [265]:
df.head(3).tail(1)

age gender name
2   35      M  tom

In [266]:
df.iloc[3]

age        33
gender      M
name      ted
Name: 3, dtype: object

In [267]:
df.iloc[3:5]

age gender  name
3   33      M   ted
4   21      F  jean

In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
age       6 non-null int64
gender    6 non-null object
name      6 non-null object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [269]:
df.describe()

age
count   6.000000
mean   26.833333
std     6.400521
min    20.000000
25%    21.500000
50%    26.000000
75%    32.000000
max    35.000000

In [270]:
df.dtypes

age        int64
gender    object
name      object
dtype: object

In [271]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [272]:
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [273]:
type(df['name'])

pandas.core.series.Series

In [274]:
df[['name', 'age']]


name  age
0  frank   29
1   mary   23
2    tom   35
3    ted   33
4   jean   21
5   lisa   20

In [275]:
df['gender']

0    M
1    F
2    M
3    M
4    F
5    F
Name: gender, dtype: object

In [276]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [277]:
df['gender'][df['gender'] == 'M']

0    M
2    M
3    M
Name: gender, dtype: object

In [278]:
df[df['gender'] == 'M']

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [279]:
(df['gender'] == 'M') & (df['age'] > 30)

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [280]:
df[(df['gender'] == 'M') & (df['age'] > 30)]

age gender name
2   35      M  tom
3   33      M  ted

In [281]:
conditions = pd.Series([True, True, False, False, True, True])
conditions

0     True
1     True
2    False
3    False
4     True
5     True
dtype: bool

In [282]:
df[conditions]

age gender   name
0   29      M  frank
1   23      F   mary
4   21      F   jean
5   20      F   lisa

In [283]:
df[(df['gender'] == 'M') | (df['age'] > 30)]

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [284]:
df['employee'] = True

In [285]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [286]:
dic = {'a':1 ,'b':2, 'c':3}
del dic['b']

In [287]:
dic

{'a': 1, 'c': 3}

In [288]:
del df['employee']
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [289]:
df['employee'] = True

In [290]:
?df.drop

In [291]:
df.drop('employee',axis = 1)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [292]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [293]:
df.drop('employee',axis = 1, inplace=True)

In [294]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [295]:
a = 5
a = 3
a

3

In [296]:
a = 5
a == 3

False

In [297]:
# a <- 3
# a == 3


In [298]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [299]:
df.loc[100] = {'age':20,'gender':'F','name':'qoo'}


In [300]:
df

age gender   name
0     29      M  frank
1     23      F   mary
2     35      M    tom
3     33      M    ted
4     21      F   jean
5     20      F   lisa
100   20      F    qoo

In [301]:
df.loc[100] = {'age':30,'gender':'F','name':'qoo'}

In [302]:
df

age  gender   name
0     29       M  frank
1     23       F   mary
2     35       M    tom
3     33       M    ted
4     21       F   jean
5     20       F   lisa
100  age  gender   name

In [303]:
df.loc[100] = [30,'F','qoo']

In [304]:
df

age gender   name
0    29      M  frank
1    23      F   mary
2    35      M    tom
3    33      M    ted
4    21      F   jean
5    20      F   lisa
100  30      F    qoo

In [306]:
df

age gender   name
0    29      M  frank
1    23      F   mary
2    35      M    tom
3    33      M    ted
4    21      F   jean
5    20      F   lisa
100  30      F    qoo

In [307]:
df = df.append(pd.DataFrame([{'age':20,'gender':'F','name':'oop'}]), ignore_index=True)


In [311]:
df.drop(7,inplace=True)

In [312]:
df

age gender   name
0  29      M  frank
1  23      F   mary
2  35      M    tom
3  33      M    ted
4  21      F   jean
5  20      F   lisa
6  30      F    qoo

In [314]:
df.drop(6,inplace=True)

In [315]:
df.index

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [316]:
df['userid'] = range(101,107)

In [320]:
df.set_index('userid', inplace=True)

In [321]:
df

age gender   name
userid                  
101     29      M  frank
102     23      F   mary
103     35      M    tom
104     33      M    ted
105     21      F   jean
106     20      F   lisa

In [322]:
df['name']

userid
101    frank
102     mary
103      tom
104      ted
105     jean
106     lisa
Name: name, dtype: object

In [323]:
df.iloc[3]

age        33
gender      M
name      ted
Name: 104, dtype: object

In [324]:
df.loc[101]

age          29
gender        M
name      frank
Name: 101, dtype: object

In [325]:
df.iloc[101]

IndexError: single positional indexer is out-of-bounds

In [326]:
df.loc[3]

KeyError: 3

In [327]:
import pandas as pd

In [328]:
df.iloc[1]

age         23
gender       F
name      mary
Name: 102, dtype: object

In [329]:
df.iloc[[1,3,5]]

age gender  name
userid                 
102     23      F  mary
104     33      M   ted
106     20      F  lisa

In [330]:
df.iloc[1:3]

age gender  name
userid                 
102     23      F  mary
103     35      M   tom

In [332]:
df.loc[[101,103]]

age gender   name
userid                  
101     29      M  frank
103     35      M    tom

In [333]:
df.loc[[101,103] , ['age', 'name']]

age   name
userid           
101     29  frank
103     35    tom

In [335]:
df.loc[[101,103]][['age', 'name']]

age   name
userid           
101     29  frank
103     35    tom

In [336]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 101 to 106
Data columns (total 3 columns):
age       6 non-null object
gender    6 non-null object
name      6 non-null object
dtypes: object(3)
memory usage: 352.0+ bytes


## Missing Value

In [337]:
import pandas as pd
import numpy  as np
df = pd.DataFrame([\
                   ['frank', 'M',    np.nan], \
                   ['mary' , np.nan, np.nan], \
                   ['tom'  , 'M',    35], \
                   ['ted'  , 'M',    33], \
                   ['jean' , np.nan, 21], \
                   ['lisa' , 'F',    20]])
df.columns = ['name', 'gender', 'age']
df


name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [339]:
df['gender'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: gender, dtype: bool

In [340]:
df['gender'].notnull()

0     True
1    False
2     True
3     True
4    False
5     True
Name: gender, dtype: bool

In [341]:
df['gender'].isnull().any()

True

In [342]:
df['gender'].isnull().all()

False

In [346]:
df.isnull().values.any()

True

In [349]:
df.isnull()

name  gender    age
0  False   False   True
1  False    True   True
2  False   False  False
3  False   False  False
4  False    True  False
5  False   False  False

In [348]:
df.isnull().sum()

name      0
gender    2
age       2
dtype: int64

In [350]:
df.isnull().sum().sum()

4

In [351]:
df

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [352]:
df.dropna()

name gender   age
2   tom      M  35.0
3   ted      M  33.0
5  lisa      F  20.0

In [354]:
df.dropna(how= 'all')

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [355]:
df.dropna(thresh=2)

name gender   age
0  frank      M   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [356]:
import numpy as np
df['employee'] = np.nan

In [357]:
df

name gender   age  employee
0  frank      M   NaN       NaN
1   mary    NaN   NaN       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean    NaN  21.0       NaN
5   lisa      F  20.0       NaN

In [358]:
# 0 => row, 1=> column
df.dropna(axis = 1, how='all')

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [360]:
df.fillna(0)

name gender   age  employee
0  frank      M   0.0       0.0
1   mary      0   0.0       0.0
2    tom      M  35.0       0.0
3    ted      M  33.0       0.0
4   jean      0  21.0       0.0
5   lisa      F  20.0       0.0

In [363]:
df['age'].mean()

27.25

In [365]:
df['age'].fillna(df['age'].mean())

0    27.25
1    27.25
2    35.00
3    33.00
4    21.00
5    20.00
Name: age, dtype: float64

In [367]:
df.groupby("gender")["age"].mean()

gender
F    20.0
M    34.0
Name: age, dtype: float64

In [366]:
# select gender, avg(age) from df group by gender
df.groupby("gender")["age"].transform("mean")

0    34.0
1     NaN
2    34.0
3    34.0
4     NaN
5    20.0
Name: age, dtype: float64

In [368]:
df['age'].fillna(df.groupby("gender")["age"].transform("mean"))


0    34.0
1     NaN
2    35.0
3    33.0
4    21.0
5    20.0
Name: age, dtype: float64

In [369]:
df

name gender   age  employee
0  frank      M   NaN       NaN
1   mary    NaN   NaN       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean    NaN  21.0       NaN
5   lisa      F  20.0       NaN

In [370]:
df.fillna(method='pad')

name gender   age  employee
0  frank      M   NaN       NaN
1   mary      M   NaN       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean      M  21.0       NaN
5   lisa      F  20.0       NaN

In [371]:
df.fillna(method='bfill')

name gender   age  employee
0  frank      M  35.0       NaN
1   mary      M  35.0       NaN
2    tom      M  35.0       NaN
3    ted      M  33.0       NaN
4   jean      F  21.0       NaN
5   lisa      F  20.0       NaN

In [372]:
df2 = pd.DataFrame([[1, 870],\
                    [2, 900],\
                    [np.nan, np.nan],\
                    [4, 950],\
                    [5,1080],\
                    [6,1200]])
df2.columns = ['time', 'val']
df2.interpolate()

time     val
0   1.0   870.0
1   2.0   900.0
2   3.0   925.0
3   4.0   950.0
4   5.0  1080.0
5   6.0  1200.0

## 資料轉換

In [373]:
import pandas as pd
?pd.read_csv

In [376]:
df = pd.read_csv('https://raw.githubusercontent.com/ywchiu/ctbcpy/master/data/rent_591.csv', index_col= 0)

In [378]:
df.head()

search_date                title       address floor_info      price  \
5   2018-05-12   近捷運，採光佳，有景觀，全新家電裝潢     新北市淡水區民族路     9F/11F  22,000元/月   
9   2018-05-14  大衛營優質社區管理好，交通便利、裝潢佳    基隆市安樂區樂利三街    14F/18F  17,000元/月   
13  2018-05-14     家樂福夜市附近，雅房出租2房2廳     嘉義市西區興業西路      7F/8F   7,500元/月   
15  2018-05-14  台北市北投新民路捷運溫泉78坪雙拼美廈     台北市北投區新民路      2F/9F  25,000元/月   
16  2018-05-13          出海口海景高樓層溫馨房  新北市淡水區中正東路一段    19F/21F  15,000元/月   

       layout  building_area building_use  
5   2房1廳1衛1陽臺          24.00    電梯大樓/整層住家  
9   2房1廳2衛2陽臺          32.00    電梯大樓/整層住家  
13  2房2廳1衛1陽臺          24.00    電梯大樓/整層住家  
15  4房3廳3衛3陽臺          78.00    電梯大樓/整層住家  
16  1房1廳1衛0陽臺          18.01    電梯大樓/整層住家

In [379]:
df.tail()

search_date                 title      address floor_info      price  \
415  2018-05-13          全新未住3+1房+雙車位  桃園市桃園區民有十二街     7F/15F  27,000元/月   
422  2018-05-12  南區新地標親家M3全新裝潢三房二廳+車位    台中市南區工學北路     8F/26F  23,000元/月   
427  2018-05-14         電梯2房優質社區生活機能佳    新北市中和區連城路    13F/16F  23,000元/月   
429  2018-05-14  大四房(4~6人)日月光/海專/高雄大學    高雄市楠梓區惠民路      4F/5F  13,300元/月   
431  2018-05-10              人本至善優質社區  台中市西屯區青海路二段     7F/14F  22,000元/月   

        layout  building_area building_use  
415  4房2廳2衛2陽臺           51.0    電梯大樓/整層住家  
422  3房2廳2衛1陽臺           50.0      公寓/整層住家  
427  2房2廳1衛1陽臺           23.1    電梯大樓/整層住家  
429  4房2廳2衛2陽臺           33.0      公寓/整層住家  
431  3房2廳2衛1陽臺           44.0      公寓/整層住家

In [380]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 8 columns):
search_date      100 non-null object
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null object
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
dtypes: float64(1), object(7)
memory usage: 7.0+ KB


In [383]:
(df['building_area'] / 0.3025).head()

5      79.338843
9     105.785124
13     79.338843
15    257.851240
16     59.537190
Name: building_area, dtype: float64

In [384]:
type(df['building_area'])

pandas.core.series.Series

In [386]:
import numpy as np
np.sqrt(df['building_area']).head()

5     4.898979
9     5.656854
13    4.898979
15    8.831761
16    4.243819
Name: building_area, dtype: float64

In [390]:
(df['address']  + df['price']).head()

5        新北市淡水區民族路22,000元/月
9       基隆市安樂區樂利三街17,000元/月
13        嘉義市西區興業西路7,500元/月
15       台北市北投區新民路25,000元/月
16    新北市淡水區中正東路一段15,000元/月
dtype: object

In [391]:
df['square_feet'] = df['building_area'] / 0.3025

In [393]:
df.head()

search_date                title       address floor_info      price  \
5   2018-05-12   近捷運，採光佳，有景觀，全新家電裝潢     新北市淡水區民族路     9F/11F  22,000元/月   
9   2018-05-14  大衛營優質社區管理好，交通便利、裝潢佳    基隆市安樂區樂利三街    14F/18F  17,000元/月   
13  2018-05-14     家樂福夜市附近，雅房出租2房2廳     嘉義市西區興業西路      7F/8F   7,500元/月   
15  2018-05-14  台北市北投新民路捷運溫泉78坪雙拼美廈     台北市北投區新民路      2F/9F  25,000元/月   
16  2018-05-13          出海口海景高樓層溫馨房  新北市淡水區中正東路一段    19F/21F  15,000元/月   

       layout  building_area building_use  square_feet  
5   2房1廳1衛1陽臺          24.00    電梯大樓/整層住家    79.338843  
9   2房1廳2衛2陽臺          32.00    電梯大樓/整層住家   105.785124  
13  2房2廳1衛1陽臺          24.00    電梯大樓/整層住家    79.338843  
15  4房3廳3衛3陽臺          78.00    電梯大樓/整層住家   257.851240  
16  1房1廳1衛0陽臺          18.01    電梯大樓/整層住家    59.537190

In [396]:
price = '22,000元/月'
int(price.replace('元/月', '').replace(',',''))

22000

In [397]:
def normalizePrice(ele):
    price = int(ele.replace('元/月', '').replace(',',''))
    return price

normalizePrice(price)

22000

In [401]:
df['price'].map(normalizePrice).head()

5     22000
9     17000
13     7500
15    25000
16    15000
Name: price, dtype: int64

In [402]:
df['price'].map(lambda e : normalizePrice(e)).head()

5     22000
9     17000
13     7500
15    25000
16    15000
Name: price, dtype: int64

In [403]:
def square(ele):
    return ele ** 2
square(3)

9

In [407]:
square = lambda ele: ele** 2
square(3)

9

In [409]:
df['price'].map(lambda ele: int(ele.replace('元/月', '').replace(',',''))).head()

5     22000
9     17000
13     7500
15    25000
16    15000
Name: price, dtype: int64

In [410]:
df = pd.DataFrame(\
[\
   [60,70,50],\
   [80,79,68],\
   [63,66,82]], \
  columns = ['First', 'Second', 'Third'])

df.apply(lambda e: e.max() - e.min(), axis=1)


0    20
1    12
2    19
dtype: int64

In [411]:
df.apply(lambda e: e.max() - e.min(), axis=0)


First     20
Second    13
Third     32
dtype: int64

In [413]:
df = pd.read_csv('https://raw.githubusercontent.com/ywchiu/ctbcpy/master/data/rent_591.csv', index_col= 0)

In [417]:
df.isnull().sum()

search_date      0
title            0
address          0
floor_info       0
price            0
layout           0
building_area    0
building_use     0
dtype: int64

In [ ]:
import numpy as np
df.applymap(lambda e: '-' if pandas.isnull(e) else e)


In [428]:
a = True
a = 1
a = {} # no
a = {'a':1}
a = [] # no
a = [1]
a = 0 # no
a = -1
a = '' # no
a = None # no
'yes' if a else 'no'

'no'

## 處理時間格式的資料

In [429]:
df = pd.read_csv('https://raw.githubusercontent.com/ywchiu/ctbcpy/master/data/rent_591.csv', index_col= 0)
df.head(3)

search_date                title     address floor_info      price  \
5   2018-05-12   近捷運，採光佳，有景觀，全新家電裝潢   新北市淡水區民族路     9F/11F  22,000元/月   
9   2018-05-14  大衛營優質社區管理好，交通便利、裝潢佳  基隆市安樂區樂利三街    14F/18F  17,000元/月   
13  2018-05-14     家樂福夜市附近，雅房出租2房2廳   嘉義市西區興業西路      7F/8F   7,500元/月   

       layout  building_area building_use  
5   2房1廳1衛1陽臺           24.0    電梯大樓/整層住家  
9   2房1廳2衛2陽臺           32.0    電梯大樓/整層住家  
13  2房2廳1衛1陽臺           24.0    電梯大樓/整層住家

In [438]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 8 columns):
search_date      100 non-null object
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null object
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
dtypes: float64(1), object(7)
memory usage: 7.0+ KB


In [440]:
from datetime import datetime
current_time = datetime.now()

In [441]:
type(current_time)

datetime.datetime

In [442]:
current_time.strftime('%Y-%m-%d')

'2019-04-22'

In [444]:
from datetime import datetime
datetime.strptime('2019-04-21', '%Y-%m-%d')

datetime.datetime(2019, 4, 21, 0, 0)

In [445]:
'2019-04-21' - '2018-05-30'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [447]:
a = datetime.strptime('2019-04-21', '%Y-%m-%d')
b = datetime.strptime('2018-05-30', '%Y-%m-%d')

In [448]:
a - b

datetime.timedelta(326)

In [449]:
from datetime import timedelta
current_time - timedelta(days = 1)

datetime.datetime(2019, 4, 21, 14, 26, 23, 671035)

In [453]:
for i in range(10):
    dt = current_time - timedelta(days = i)
    print(dt.strftime('%Y-%m-%d'))

2019-04-22
2019-04-21
2019-04-20
2019-04-19
2019-04-18
2019-04-17
2019-04-16
2019-04-15
2019-04-14
2019-04-13


In [454]:
from time import mktime
mktime(current_time.timetuple())


1555914383.0

In [455]:
datetime.fromtimestamp(1555860118)

datetime.datetime(2019, 4, 21, 23, 21, 58)

In [486]:
from datetime import datetime, timedelta
dt_str = '2019-01-01'
ary = []
dt = datetime.strptime(dt_str,  '%Y-%m-%d')
for i in range(365):
    ct = dt+timedelta(days = i)
    if ct.weekday() == 4:
        ary.append([ct, ct.month])

In [488]:
import pandas
df2 = pandas.DataFrame(ary)
df2.columns = ['dt', 'mon']
df3 = df2.groupby('mon')['dt'].max()

In [501]:
df2.groupby('mon')['dt'].max().map(lambda e: 'major_' + e.strftime('%Y-%m-%d') + '.csv')

mon
1     major_2019-01-25.csv
2     major_2019-02-22.csv
3     major_2019-03-29.csv
4     major_2019-04-26.csv
5     major_2019-05-31.csv
6     major_2019-06-28.csv
7     major_2019-07-26.csv
8     major_2019-08-30.csv
9     major_2019-09-27.csv
10    major_2019-10-25.csv
11    major_2019-11-29.csv
12    major_2019-12-27.csv
Name: dt, dtype: object

In [497]:
['major_' + e + '.csv' for e in df3.astype(str).values.tolist()]

['major_2019-01-25.csv',
 'major_2019-02-22.csv',
 'major_2019-03-29.csv',
 'major_2019-04-26.csv',
 'major_2019-05-31.csv',
 'major_2019-06-28.csv',
 'major_2019-07-26.csv',
 'major_2019-08-30.csv',
 'major_2019-09-27.csv',
 'major_2019-10-25.csv',
 'major_2019-11-29.csv',
 'major_2019-12-27.csv']

In [504]:
df['dt'] = pd.to_datetime(df['search_date'], format= '%Y-%m-%d')


In [505]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 9 columns):
search_date      100 non-null object
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null object
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
dt               100 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 7.8+ KB


In [511]:
df = pd.read_csv('https://raw.githubusercontent.com/ywchiu/ctbcpy/master/data/rent_591.csv', index_col= 0, parse_dates=[1])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 8 columns):
search_date      100 non-null datetime64[ns]
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null object
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 7.0+ KB
