## List

In [1]:
a = [1,2,3,4,5]
type(a)

list

In [2]:
a.append('Hello')
a

[1, 2, 3, 4, 5, 'Hello']

In [5]:
a[0] + 10 

11

In [7]:
a[-1] + ' World'

'Hello World'

In [8]:
a = [1,3,5,7, 9]
b = [2,4,6,8,10]

In [9]:
#[1 + 2, 3 + 4 ,5 +6 ...]
len(a)

5

In [10]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [11]:
for i in range(len(a)):
    print(a[i])

1
3
5
7
9


In [12]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [13]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [14]:
zip(a,b)

In [15]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [16]:
for rec in zip(a,b):
    print(rec[0] + rec[1])

3
7
11
15
19


In [17]:
for i,j in zip(a,b):
    print(i + j)

3
7
11
15
19


In [18]:
ary = []
for i,j in zip(a,b):
    ary.append(i + j)
ary

[3, 7, 11, 15, 19]

In [20]:
[i + j for  i,j in zip(a,b)]

[3, 7, 11, 15, 19]

In [22]:
import numpy
na = numpy.array(a)
nb = numpy.array(b)

In [23]:
na + nb

array([ 3,  7, 11, 15, 19])

In [24]:
na * nb

array([ 2, 12, 30, 56, 90])

In [25]:
import numpy as np

In [26]:
na = np.array([1, 2, 3, 4, 5])
na

array([1, 2, 3, 4, 5])

In [27]:
na[0]

1

In [28]:
na[-1]

5

In [29]:
na[1:3]

array([2, 3])

In [30]:
na

array([1, 2, 3, 4, 5])

In [31]:
na > 3

array([False, False, False,  True,  True])

In [32]:
na[na > 3]

array([4, 5])

In [34]:
na = np.array([
[1,2,3,4, 5],
[6,7,8,9, 10]])

In [35]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
na.shape

(2, 5)

In [37]:
na[0,0]

1

In [38]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
na[:,0]

array([1, 6])

In [40]:
na[0,:]

array([1, 2, 3, 4, 5])

In [41]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
type(na)

numpy.ndarray

In [44]:
a = [1,2,3,4,5, 'hello']
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U11')

In [46]:
#  [ 1, 2      X    [2,
#    3, 4 ]          3]

#    2 X 2     X     2 * 1
na = np.array([[1,2],[3,4]])
nb = np.array([2,3])
np.dot(na , nb)

array([ 8, 18])

In [47]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

## Pandas

In [48]:
li = [['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [49]:
li

[['frank', 'M', 29],
 ['mary', 'F', 23],
 ['tom', 'M', 35],
 ['ted', 'M', 33],
 ['jean', 'F', 21],
 ['lisa', 'F', 20]]

In [50]:
type(li)

list

In [51]:
import numpy as np
np.array(li)

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [52]:
m = np.array(li)
m[:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U5')

In [54]:
m[:,2].astype(int).sum()

161

In [55]:
li = [['name', 'gender', 'age'],['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [62]:
na = np.array(li)

In [67]:
na[:,2][1:].astype(int).sum()

161

## Pandas

In [69]:
import pandas as pd

In [71]:
df = pd.DataFrame([['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [72]:
df.loc[3,0]

'ted'

In [73]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [74]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [76]:
df['age'].mean()

26.833333333333332

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
name      6 non-null object
gender    6 non-null object
age       6 non-null int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


## Pandas Series

In [78]:
import numpy as np
a = [1,2,3,4,5]
na = np.array(a)
na

array([1, 2, 3, 4, 5])

In [79]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [80]:
a = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
a

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [81]:
import pandas as pd
s = pd.Series([42000, 38000, 56000])
s

0    42000
1    38000
2    56000
dtype: int64

In [82]:
import pandas as pd
s = pd.Series([42000, 38000, 56000], index=['John', 'Marry', 'Sam'])
s

John     42000
Marry    38000
Sam      56000
dtype: int64

In [83]:
s = pd.Series({'John':42000,'Marry':38000,'Sam':56000})
s


John     42000
Marry    38000
Sam      56000
dtype: int64

In [84]:
s[2]

56000

In [85]:
s[1:3]

Marry    38000
Sam      56000
dtype: int64

In [86]:
s

John     42000
Marry    38000
Sam      56000
dtype: int64

In [87]:
s['Sam']

56000

In [88]:
s[['Sam', 'John']]

Sam     56000
John    42000
dtype: int64

In [89]:
s < 40000

John     False
Marry     True
Sam      False
dtype: bool

In [90]:
s[s < 40000]

Marry    38000
dtype: int64

In [92]:
criteria = np.array([False, True, True])
s[criteria]

Marry    38000
Sam      56000
dtype: int64

In [93]:
s < 40000

John     False
Marry     True
Sam      False
dtype: bool

In [94]:
cheap = s < 40000

In [95]:
s[cheap]

Marry    38000
dtype: int64

In [97]:
s['Marry'] = 40000

In [98]:
s

John     42000
Marry    40000
Sam      56000
dtype: int64

In [100]:
s[s==40000] = s[s==40000] * 1.1

In [101]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [102]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [103]:
'David' in s

False

In [104]:
'John' in s

True

In [105]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [106]:
s * 0.8

John     33600.0
Marry    35200.0
Sam      44800.0
dtype: float64

In [107]:
np.sqrt(s)

John     204.939015
Marry    209.761770
Sam      236.643191
dtype: float64

In [108]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [110]:
s.max()

56000

In [111]:
s.min()

42000

In [112]:
s.sum()

142000

In [113]:
s.mean()

47333.333333333336

In [114]:
s.describe()

count        3.000000
mean     47333.333333
std       7571.877794
min      42000.000000
25%      43000.000000
50%      44000.000000
75%      50000.000000
max      56000.000000
dtype: float64

In [116]:
s[['Marry', 'Jane']]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:850: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


Marry    44000.0
Jane         NaN
dtype: float64

In [117]:
s[['John','Marry']]

John     42000
Marry    44000
dtype: int64

In [119]:
s2 = s[['Marry', 'Jane']] + s[['John','Marry']]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:850: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


In [121]:
s2.isnull()

Jane      True
John      True
Marry    False
dtype: bool

In [122]:
s2.notnull()

Jane     False
John     False
Marry     True
dtype: bool

## Pandas DataFrame

In [123]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M', 35],['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]])

In [124]:
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [125]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [126]:
df.columns = ['name', 'gender', 'age']

In [127]:
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [128]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted','M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]], 
    columns = ['name', 'gender', 'age'])

In [129]:
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [130]:
df = pd.DataFrame([{
    'name':'frank','gender':'M', 'age':29}, \
{'name':'mary','gender':'F', 'age':23}, \
{'name':'tom','gender':'M', 'age':35}, \
{'name':'ted','gender':'M', 'age':33}, \
{'name':'jean','gender':'F', 'age':21}, \
{'name':'lisa','gender':'F', 'age':20}])

In [132]:
df2 = pd.DataFrame([{
    'name':'frank','gender':'M', 'age':29}, \
{'name':'mary','gender':'F', 'age':23}, \
{'name':'tom','gender':'M'}, \
{'name':'ted','gender':'M', 'age':33}, \
{'name':'jean','gender':'F', 'age':21}, \
{'name':'lisa','gender':'F' }])
df2

age gender   name
0  29.0      M  frank
1  23.0      F   mary
2   NaN      M    tom
3  33.0      M    ted
4  21.0      F   jean
5   NaN      F   lisa

In [134]:
# R:      head(df)
# Python: df.head()
df.head()

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean

In [135]:
?df.head()

In [136]:
df.head(3)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom

In [137]:
df.tail()

age gender  name
1   23      F  mary
2   35      M   tom
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
age       6 non-null int64
gender    6 non-null object
name      6 non-null object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [139]:
df.describe()

age
count   6.000000
mean   26.833333
std     6.400521
min    20.000000
25%    21.500000
50%    26.000000
75%    32.000000
max    35.000000

In [141]:
df.dtypes

age        int64
gender    object
name      object
dtype: object

In [143]:
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [144]:
df[['name', 'age']]

name  age
0  frank   29
1   mary   23
2    tom   35
3    ted   33
4   jean   21
5   lisa   20

In [145]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [147]:
df[df['gender']=='M']

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [148]:
df['gender']=='M' 

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [149]:
df['age'] > 30

0    False
1    False
2     True
3     True
4    False
5    False
Name: age, dtype: bool

In [150]:
(df['gender']=='M' ) & (df['age'] > 30)

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [151]:
df[(df['gender']=='M' ) & (df['age'] > 30)]

age gender name
2   35      M  tom
3   33      M  ted

In [152]:
df[(df['gender']=='M' ) | (df['age'] > 30)]

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [154]:
df['employee'] = True

In [155]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [156]:
a = 5
a + 3

8

In [157]:
del a

In [158]:
a + 3

NameError: name 'a' is not defined

In [159]:
del df['employee']

In [161]:
df['employee'] = True

In [166]:
?df.drop

In [167]:
df.drop('employee', axis = 1, inplace=True)

In [168]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [169]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [170]:
df.loc[8] = {'age':20, 'name':'qoo', 'gender': 'M'}

In [171]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa
8   20      M    qoo

In [177]:
df = df.append(pd.DataFrame([{'age':26,'gender':'F','name':'jane'}]),
ignore_index=True)


In [178]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa
6   20      M    qoo
7   26      F   jane

In [181]:
df.drop(6, axis = 0, inplace=True )

In [184]:
df.index

Int64Index([0, 1, 2, 3, 4, 5, 7], dtype='int64')

In [186]:
df['userid'] = range(101,108)

In [187]:
df

age gender   name  userid
0   29      M  frank     101
1   23      F   mary     102
2   35      M    tom     103
3   33      M    ted     104
4   21      F   jean     105
5   20      F   lisa     106
7   26      F   jane     107

In [188]:
df.set_index('userid', inplace=True)

In [190]:
df

age gender   name
userid                   
101      29      M  frank
102      23      F   mary
103      35      M    tom
104      33      M    ted
105      21      F   jean
106      20      F   lisa
107      26      F   jane

In [192]:
# loc: get data by index name
df.loc[103]

age        35
gender      M
name      tom
Name: 103, dtype: object

In [193]:
# iloc: get data by index position
df.iloc[2]

age        35
gender      M
name      tom
Name: 103, dtype: object

In [194]:
df.iloc[[1,3,5]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [195]:
df.loc[[102,104,106]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [198]:
df.reset_index(inplace=True)

In [203]:
df.iloc[0,0:3]

userid    101
age        29
gender      M
Name: 0, dtype: object

In [205]:
df.iloc[0,:].tolist()

[101, 29, 'M', 'frank']

## Missing Value

In [206]:
import numpy as np
np.nan

nan

In [207]:
import pandas as pd
import numpy as np
df = pd.DataFrame([\
['frank', 'M', np.nan], \
['mary', np.nan, np.nan], \
['tom' , 'M', 35], \
['ted' , 'M', 33], \
['jean' , np.nan, 21], \
['lisa', 'F', 20]])
df.columns = ['name', 'gender', 'age']
df

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [208]:
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [210]:
df['name'].isnull().sum()

0

In [212]:
df['name'].notnull().sum()

6

In [214]:
# False : 0 
# True  : 1
df['name'].notnull().sum()

6

In [217]:
df['gender'].isnull().sum()

2

In [218]:
df['age'].isnull().sum()

2

In [219]:
df.isnull()

name  gender    age
0  False   False   True
1  False    True   True
2  False   False  False
3  False   False  False
4  False    True  False
5  False   False  False

In [220]:
df.isnull().sum()

name      0
gender    2
age       2
dtype: int64

In [221]:
df.name.isnull().values.any()

False

In [222]:
df.isnull().values.any()

True

In [223]:
df.isnull().sum()


name      0
gender    2
age       2
dtype: int64

In [224]:
df.isnull().sum().sum()

4

In [226]:
# df.dropna(inplace = True)
df.dropna()


name gender   age
2   tom      M  35.0
3   ted      M  33.0
5  lisa      F  20.0

In [228]:
df.dropna(how = 'all')

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [229]:
df.dropna(thresh=2)

name gender   age
0  frank      M   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [233]:
df['employee'] = np.nan

In [236]:
df.dropna(axis = 1, how='all', inplace=True)

In [239]:
df.fillna(0)

name gender   age
0  frank      M   0.0
1   mary      0   0.0
2    tom      M  35.0
3    ted      M  33.0
4   jean      0  21.0
5   lisa      F  20.0

In [240]:
df['age'].fillna(0)
# df['age'] = df['age'].fillna(0)

0     0.0
1     0.0
2    35.0
3    33.0
4    21.0
5    20.0
Name: age, dtype: float64

In [242]:
df['age'].mean()

27.25

In [243]:
df['age'].fillna(df['age'].mean())

0    27.25
1    27.25
2    35.00
3    33.00
4    21.00
5    20.00
Name: age, dtype: float64

In [245]:
# SELECT gender, AVG(age) FROM df GROUP BY gender
df.groupby('gender')['age'].mean()

gender
F    20.0
M    34.0
Name: age, dtype: float64

In [246]:
df.groupby('gender')['age'].transform('mean')

0    34.0
1     NaN
2    34.0
3    34.0
4     NaN
5    20.0
Name: age, dtype: float64

In [247]:
df['age'].fillna(df.groupby('gender')['age'].transform('mean'))

0    34.0
1     NaN
2    35.0
3    33.0
4    21.0
5    20.0
Name: age, dtype: float64

In [250]:
df

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [251]:
df.fillna(method='pad')

name gender   age
0  frank      M   NaN
1   mary      M   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean      M  21.0
5   lisa      F  20.0

In [253]:
df.fillna(method='bfill', limit=2)

name gender   age
0  frank      M  35.0
1   mary      M  35.0
2    tom      M  35.0
3    ted      M  33.0
4   jean      F  21.0
5   lisa      F  20.0

In [255]:
df2 = pd.DataFrame([[1, 870],\
[2, 900],\
[np.nan, np.nan],\
[4, 950],\
[5,1080],\
[6,1200]])
df2

0       1
0  1.0   870.0
1  2.0   900.0
2  NaN     NaN
3  4.0   950.0
4  5.0  1080.0
5  6.0  1200.0

In [256]:
df2.columns = ['time','val']

In [257]:
df2.interpolate()

time     val
0   1.0   870.0
1   2.0   900.0
2   3.0   925.0
3   4.0   950.0
4   5.0  1080.0
5   6.0  1200.0

## 資料轉換

In [262]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/ctbcpy/master/data/rent_591.csv', index_col = 0)
df.head()

search_date                title       address floor_info      price  \
5   2018-05-12   近捷運，採光佳，有景觀，全新家電裝潢     新北市淡水區民族路     9F/11F  22,000元/月   
9   2018-05-14  大衛營優質社區管理好，交通便利、裝潢佳    基隆市安樂區樂利三街    14F/18F  17,000元/月   
13  2018-05-14     家樂福夜市附近，雅房出租2房2廳     嘉義市西區興業西路      7F/8F   7,500元/月   
15  2018-05-14  台北市北投新民路捷運溫泉78坪雙拼美廈     台北市北投區新民路      2F/9F  25,000元/月   
16  2018-05-13          出海口海景高樓層溫馨房  新北市淡水區中正東路一段    19F/21F  15,000元/月   

       layout  building_area building_use  
5   2房1廳1衛1陽臺          24.00    電梯大樓/整層住家  
9   2房1廳2衛2陽臺          32.00    電梯大樓/整層住家  
13  2房2廳1衛1陽臺          24.00    電梯大樓/整層住家  
15  4房3廳3衛3陽臺          78.00    電梯大樓/整層住家  
16  1房1廳1衛0陽臺          18.01    電梯大樓/整層住家

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 8 columns):
search_date      100 non-null object
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null object
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
dtypes: float64(1), object(7)
memory usage: 7.0+ KB


In [265]:
#df['price']

In [268]:
df['square_feet'] = df['building_area'] / 0.3025

In [270]:
'22,000元/月'

'22,000元/月'

In [273]:
int('22,000元/月'.replace('元/月', '').replace(',',''))

22000

In [274]:
def normalizePrice(ele):
    return int(ele.replace('元/月', '').replace(',',''))

In [275]:
normalizePrice('22,000元/月')

22000

In [278]:
#df['price'].map(normalizePrice)

In [279]:
def square(e):
    return e ** 2

square(3)

9

In [280]:
square = lambda e: e ** 2
square(4)

16

In [282]:
df['price'] = df['price'].map(lambda ele: int(ele.replace('元/月', '').replace(',','')))

In [283]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 5 to 431
Data columns (total 9 columns):
search_date      100 non-null object
title            100 non-null object
address          100 non-null object
floor_info       100 non-null object
price            100 non-null int64
layout           100 non-null object
building_area    100 non-null float64
building_use     100 non-null object
square_feet      100 non-null float64
dtypes: float64(2), int64(1), object(6)
memory usage: 7.8+ KB


In [285]:
df['price'].describe()

count      100.000000
mean     20502.000000
std      11311.333192
min       7000.000000
25%      14000.000000
50%      17750.000000
75%      23250.000000
max      75000.000000
Name: price, dtype: float64

In [287]:
(df['price'] / df['building_area']).describe()

count     100.000000
mean      601.097570
std       304.803446
min        75.000000
25%       412.396978
50%       544.374223
75%       679.833680
max      2000.000000
dtype: float64

In [289]:
df = pandas.DataFrame(\
[\
[60,70,50],\
[80,79,68],\
[63,66,82]], \
columns = ['First', 'Second', 'Third'])

df

First  Second  Third
0     60      70     50
1     80      79     68
2     63      66     82

In [290]:
df.apply(lambda e: e.max() - e.min(), axis=1)

0    20
1    12
2    19
dtype: int64

In [291]:
df.apply(lambda e: e.max() - e.min(), axis=0)

First     20
Second    13
Third     32
dtype: int64

In [293]:
import pandas as pd
import numpy as np
df = pd.DataFrame([\
['frank', 'M', np.nan], \
['mary', np.nan, np.nan], \
['tom' , 'M', 35], \
['ted' , 'M', 33], \
['jean' , np.nan, 21], \
['lisa', 'F', 20]])
df.columns = ['name', 'gender', 'age']
df

name gender   age
0  frank      M   NaN
1   mary    NaN   NaN
2    tom      M  35.0
3    ted      M  33.0
4   jean    NaN  21.0
5   lisa      F  20.0

In [294]:
df.fillna('-')

name gender age
0  frank      M   -
1   mary      -   -
2    tom      M  35
3    ted      M  33
4   jean      -  21
5   lisa      F  20

In [ ]:
def f(e):
    if pd.isnull(e):
        return '-'
    else:
        return e

In [295]:
df.applymap(lambda e: '-' if pd.isnull(e) else e)

name gender age
0  frank      M   -
1   mary      -   -
2    tom      M  35
3    ted      M  33
4   jean      -  21
5   lisa      F  20